/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Car {
  'model' : string,
  'make' : string,
  'mods' : Array<string>,
  'year' : bigint,
}
export type Principal = Principal;
export interface RaceEvent {
  'winner' : string,
  'timestamp' : Time,
  'challenged' : string,
  'challenger' : string,
}
export interface RacerProfile {
  'bio' : string,
  'name' : string,
  'wins' : bigint,
  'losses' : bigint,
  'reputation' : bigint,
  'avatarUrl' : [] | [string],
}
export type Time = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'acceptChallenge' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'completeChallenge' : ActorMethod<[bigint, Principal], undefined>,
  'createChallenge' : ActorMethod<[Principal], bigint>,
  'getActivityFeed' : ActorMethod<[], Array<RaceEvent>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [RacerProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCar' : ActorMethod<[Principal], [] | [Car]>,
  'getLeaderboard' : ActorMethod<[], Array<RacerProfile>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [RacerProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerCar' : ActorMethod<
    [string, string, bigint, Array<string>],
    undefined
  >,
  'saveCallerUserProfile' : ActorMethod<
    [string, string, [] | [string]],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];