/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Principal = IDL.Principal;
export const RaceResult = IDL.Record({
  'winnerHp' : IDL.Nat,
  'winnerXp' : IDL.Nat,
  'winner' : Principal,
  'loserHp' : IDL.Nat,
  'loserXp' : IDL.Nat,
  'loser' : Principal,
  'challengeId' : IDL.Nat,
  'winnerName' : IDL.Text,
  'loserName' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const RacerProfile = IDL.Record({
  'xp' : IDL.Nat,
  'bio' : IDL.Text,
  'name' : IDL.Text,
  'wins' : IDL.Nat,
  'losses' : IDL.Nat,
  'reputation' : IDL.Int,
  'speed' : IDL.Nat,
  'avatarUrl' : IDL.Opt(IDL.Text),
});
export const Time = IDL.Int;
export const RaceEvent = IDL.Record({
  'winner' : IDL.Text,
  'timestamp' : Time,
  'challenged' : IDL.Text,
  'challenger' : IDL.Text,
});
export const Car = IDL.Record({
  'hp' : IDL.Nat,
  'model' : IDL.Text,
  'make' : IDL.Text,
  'mods' : IDL.Vec(IDL.Text),
  'year' : IDL.Nat,
});
export const ChatMessage = IDL.Record({
  'id' : IDL.Nat,
  'text' : IDL.Text,
  'timestamp' : Time,
  'senderName' : IDL.Text,
  'roomId' : IDL.Text,
  'senderId' : IDL.Text,
});
export const ChatRoom = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'createdBy' : IDL.Text,
  'isCustom' : IDL.Bool,
});
export const ChallengeStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'accepted' : IDL.Null,
  'declined' : IDL.Null,
});
export const RaceChallenge = IDL.Record({
  'id' : IDL.Nat,
  'status' : ChallengeStatus,
  'winner' : IDL.Opt(Principal),
  'timestamp' : Time,
  'challenged' : Principal,
  'challenger' : Principal,
});
export const Task = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'xpReward' : IDL.Nat,
  'requiredCompletions' : IDL.Nat,
  'description' : IDL.Text,
});
export const XpEvent = IDL.Record({
  'raceLabel' : IDL.Text,
  'streakBonus' : IDL.Bool,
  'timestamp' : Time,
  'amount' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'acceptAndRaceChallenge' : IDL.Func([IDL.Nat], [RaceResult], []),
  'acceptChallenge' : IDL.Func([IDL.Nat], [], []),
  'addXpEvent' : IDL.Func([IDL.Text, IDL.Nat, IDL.Bool], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'claimDailyChallenge' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'completeChallenge' : IDL.Func([IDL.Nat, Principal], [], []),
  'completeTask' : IDL.Func([], [RacerProfile], []),
  'createChallenge' : IDL.Func([Principal], [IDL.Nat], []),
  'createChatRoom' : IDL.Func([IDL.Text], [], []),
  'deleteChatRoom' : IDL.Func([IDL.Text], [], []),
  'findRandomOpponent' : IDL.Func(
      [],
      [
        IDL.Opt(
          IDL.Record({ 'principal' : IDL.Text, 'profile' : RacerProfile })
        ),
      ],
      [],
    ),
  'getActivityFeed' : IDL.Func([], [IDL.Vec(RaceEvent)], ['query']),
  'getAllRacerProfiles' : IDL.Func(
      [],
      [
        IDL.Vec(
          IDL.Record({ 'principal' : IDL.Text, 'profile' : RacerProfile })
        ),
      ],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(RacerProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCar' : IDL.Func([Principal], [IDL.Opt(Car)], ['query']),
  'getCarHp' : IDL.Func([Principal], [IDL.Nat], ['query']),
  'getChatMessages' : IDL.Func([IDL.Text], [IDL.Vec(ChatMessage)], ['query']),
  'getChatRooms' : IDL.Func([], [IDL.Vec(ChatRoom)], ['query']),
  'getDailyProgress' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Nat)], ['query']),
  'getIncomingChallenges' : IDL.Func([], [IDL.Vec(RaceChallenge)], ['query']),
  'getLeaderboard' : IDL.Func([], [IDL.Vec(RacerProfile)], ['query']),
  'getOutgoingChallenges' : IDL.Func([], [IDL.Vec(RaceChallenge)], ['query']),
  'getRoomMembers' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getStreak' : IDL.Func([], [IDL.Nat], ['query']),
  'getTaskProgress' : IDL.Func(
      [],
      [
        IDL.Record({
          'tasks' : IDL.Vec(Task),
          'completionsOnCurrentTask' : IDL.Nat,
          'currentTaskId' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getUserProfile' : IDL.Func([Principal], [IDL.Opt(RacerProfile)], ['query']),
  'getXpHistory' : IDL.Func([], [IDL.Vec(XpEvent)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'joinRoom' : IDL.Func([IDL.Text], [], []),
  'leaveRoom' : IDL.Func([IDL.Text], [], []),
  'migrateDefaultRooms' : IDL.Func([], [], []),
  'registerCar' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Vec(IDL.Text), IDL.Nat],
      [],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([RacerProfile], [], []),
  'searchRacerByName' : IDL.Func(
      [IDL.Text],
      [
        IDL.Vec(
          IDL.Record({ 'principal' : IDL.Text, 'profile' : RacerProfile })
        ),
      ],
      ['query'],
    ),
  'sendChatMessage' : IDL.Func([IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Principal = IDL.Principal;
  const RaceResult = IDL.Record({
    'winnerHp' : IDL.Nat,
    'winnerXp' : IDL.Nat,
    'winner' : Principal,
    'loserHp' : IDL.Nat,
    'loserXp' : IDL.Nat,
    'loser' : Principal,
    'challengeId' : IDL.Nat,
    'winnerName' : IDL.Text,
    'loserName' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const RacerProfile = IDL.Record({
    'xp' : IDL.Nat,
    'bio' : IDL.Text,
    'name' : IDL.Text,
    'wins' : IDL.Nat,
    'losses' : IDL.Nat,
    'reputation' : IDL.Int,
    'speed' : IDL.Nat,
    'avatarUrl' : IDL.Opt(IDL.Text),
  });
  const Time = IDL.Int;
  const RaceEvent = IDL.Record({
    'winner' : IDL.Text,
    'timestamp' : Time,
    'challenged' : IDL.Text,
    'challenger' : IDL.Text,
  });
  const Car = IDL.Record({
    'hp' : IDL.Nat,
    'model' : IDL.Text,
    'make' : IDL.Text,
    'mods' : IDL.Vec(IDL.Text),
    'year' : IDL.Nat,
  });
  const ChatMessage = IDL.Record({
    'id' : IDL.Nat,
    'text' : IDL.Text,
    'timestamp' : Time,
    'senderName' : IDL.Text,
    'roomId' : IDL.Text,
    'senderId' : IDL.Text,
  });
  const ChatRoom = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'createdBy' : IDL.Text,
    'isCustom' : IDL.Bool,
  });
  const ChallengeStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'accepted' : IDL.Null,
    'declined' : IDL.Null,
  });
  const RaceChallenge = IDL.Record({
    'id' : IDL.Nat,
    'status' : ChallengeStatus,
    'winner' : IDL.Opt(Principal),
    'timestamp' : Time,
    'challenged' : Principal,
    'challenger' : Principal,
  });
  const Task = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'xpReward' : IDL.Nat,
    'requiredCompletions' : IDL.Nat,
    'description' : IDL.Text,
  });
  const XpEvent = IDL.Record({
    'raceLabel' : IDL.Text,
    'streakBonus' : IDL.Bool,
    'timestamp' : Time,
    'amount' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'acceptAndRaceChallenge' : IDL.Func([IDL.Nat], [RaceResult], []),
    'acceptChallenge' : IDL.Func([IDL.Nat], [], []),
    'addXpEvent' : IDL.Func([IDL.Text, IDL.Nat, IDL.Bool], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'claimDailyChallenge' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'completeChallenge' : IDL.Func([IDL.Nat, Principal], [], []),
    'completeTask' : IDL.Func([], [RacerProfile], []),
    'createChallenge' : IDL.Func([Principal], [IDL.Nat], []),
    'createChatRoom' : IDL.Func([IDL.Text], [], []),
    'deleteChatRoom' : IDL.Func([IDL.Text], [], []),
    'findRandomOpponent' : IDL.Func(
        [],
        [
          IDL.Opt(
            IDL.Record({ 'principal' : IDL.Text, 'profile' : RacerProfile })
          ),
        ],
        [],
      ),
    'getActivityFeed' : IDL.Func([], [IDL.Vec(RaceEvent)], ['query']),
    'getAllRacerProfiles' : IDL.Func(
        [],
        [
          IDL.Vec(
            IDL.Record({ 'principal' : IDL.Text, 'profile' : RacerProfile })
          ),
        ],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(RacerProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCar' : IDL.Func([Principal], [IDL.Opt(Car)], ['query']),
    'getCarHp' : IDL.Func([Principal], [IDL.Nat], ['query']),
    'getChatMessages' : IDL.Func([IDL.Text], [IDL.Vec(ChatMessage)], ['query']),
    'getChatRooms' : IDL.Func([], [IDL.Vec(ChatRoom)], ['query']),
    'getDailyProgress' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Nat)], ['query']),
    'getIncomingChallenges' : IDL.Func([], [IDL.Vec(RaceChallenge)], ['query']),
    'getLeaderboard' : IDL.Func([], [IDL.Vec(RacerProfile)], ['query']),
    'getOutgoingChallenges' : IDL.Func([], [IDL.Vec(RaceChallenge)], ['query']),
    'getRoomMembers' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getStreak' : IDL.Func([], [IDL.Nat], ['query']),
    'getTaskProgress' : IDL.Func(
        [],
        [
          IDL.Record({
            'tasks' : IDL.Vec(Task),
            'completionsOnCurrentTask' : IDL.Nat,
            'currentTaskId' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [Principal],
        [IDL.Opt(RacerProfile)],
        ['query'],
      ),
    'getXpHistory' : IDL.Func([], [IDL.Vec(XpEvent)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'joinRoom' : IDL.Func([IDL.Text], [], []),
    'leaveRoom' : IDL.Func([IDL.Text], [], []),
    'migrateDefaultRooms' : IDL.Func([], [], []),
    'registerCar' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Vec(IDL.Text), IDL.Nat],
        [],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([RacerProfile], [], []),
    'searchRacerByName' : IDL.Func(
        [IDL.Text],
        [
          IDL.Vec(
            IDL.Record({ 'principal' : IDL.Text, 'profile' : RacerProfile })
          ),
        ],
        ['query'],
      ),
    'sendChatMessage' : IDL.Func([IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };